builds:
  - dir: openweather-exporter
    env:
      - GO111MODULE=on
      - CGO_ENABLED=0
    goos:
    - linux
    goarch:
    - arm
    goarm:
    - '7'
    no_unique_dist_dir: true
    binary: openweather-exporter/app
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

dockers:
  - goos: linux
    goarch: arm
    goarm: '7'
    image_templates:
    - "legnoh/openweather-exporter:latest"
    - "legnoh/openweather-exporter:{{ .Tag }}"
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
    - "--pull"
    - "--platform=linux/arm/v7"
